services:
  db:
    build:
      dockerfile: ./test-db.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 10